# Makefile for custom library modules for the free version
# (c) 2005 Robert Spalek <robert@ucw.cz>

DIRS+=free/lib

CUSTOM_LIB_MODULES+=$(o)/free/lib/custom

# If your custom modules depend on any Sherlock libraries, list
# their *.pc files here.
#CUSTOM_LIB_DEPS=

# If they depend on any third-party libraries, list the linker flags here.
#CUSTOM_LIB_EXTRAS=
